name: Run Newman API Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman tests
        run: |
          newman run "collections/QA-Portfolio-Project.postman_collection.json" \
            -e "environments/QA-Portfolio-Project.postman_environment.json" \
            --env-var "githubToken=${{ secrets.PAT_TOKEN }}" \
            --reporters cli,junit \
            --reporter-junit-export reports/results.xml

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-results
          path: reports/results.xml